# Generated by Django 4.0.6 on 2022-07-15 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('client_Name', models.CharField(max_length=100)),
                ('priority', models.CharField(max_length=100)),
                ('target_Date', models.DateField()),
                ('product_Area', models.CharField(max_length=100)),
            ],
        ),
    ]
